"""add generated_images table

Revision ID: 93deab5bd5c7
Revises: 9252c0b3a480
Create Date: 2026-07-08 17:28:46.139024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93deab5bd5c7'
down_revision: Union[str, Sequence[str], None] = '9252c0b3a480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence_index >= 1', name='chk_generated_image_sequence_index_positive'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'sequence_index', name='uq_generated_image_video_sequence')
    )
    op.create_index(op.f('ix_generated_images_video_id'), 'generated_images', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_images_video_id'), table_name='generated_images')
    op.drop_table('generated_images')
    # ### end Alembic commands ###
