"""add rendered_video_path to videos

Revision ID: d8a75eb911aa
Revises: 93deab5bd5c7
Create Date: 2026-07-08 17:58:17.248888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a75eb911aa'
down_revision: Union[str, Sequence[str], None] = '93deab5bd5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('rendered_video_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'rendered_video_path')
    # ### end Alembic commands ###
